# Setup
title: Ethan Xue
tagline: Lifelong Learner | SWE | Human Being
baseurl: ""
paginate: 1
locale: "en"

# About
author:
  name: Ethan Xue
  email_address: ethan.xue@gmail.com
  github: exue026
  linkedin: ethanxue026

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
